В первую очередь хочу отметить, то что main это не более чем обычный метод, и да, он вызывается виртуальной машиной для
начала выполнения программы, но кроме этого он может быть вызван и из любого другого кода.

То есть на него также распространяются обычные правила указания выбрасываемых проверяемых исключений (checked
exceptions) после throws:

``public static void main(String[] args) throws IOException {``

Соответственно в нем тоже могут падать исключения.

Если main не был вызван в каком-то методе, а был запущен как точка запуска программы, то выброшенное им исключение будет
обрабатываться перехватчиком .UncaughtExceptionHandler.

Данный обработчик один на свой поток (то есть по одному обработчику в каждом потоке). При надобности можно создать свой
обработчик и задать его с помощью метода setDefaultUncaughtExceptionHandler, вызванного у объекта Thread.